### ISSUE TITLE
Profile and re-structure the game code to improve framerate

### ISSUE THREAD

**Issue by ghost** [Seneca-CDOT/thecollectors#101]
The game has become visibly slower when the vehicle drives across roads, and this worries me. Profiling will help identify areas where the game code is doing too much or being inefficient at what it is doing.

**Comment by ghost** [comment]
The biggest hit on performance has been the newly merged tint() functionality. I have reverted that and have instead added a 50% alpha version of all buildings to the game, and set up the game code to swap to those new images when a delivery has been complete (Fuel Stations are currently exempt). This results in a much smoother game experience.

Pull request isn't yet ready as there are some questions that must be answered first. This is to inform everyone that the issue has been solved by using svg images with alpha and that no more work to solve the tint() issue is necessary.

**Comment by dsegna** [comment]
Did you try making it only tint when the alpha value was anything other than 255? This would likely solve the performance issue with tint, without having to double the number of images.

UPDATE : Only calling tint when the alpha value is less than 255 did significantly improve the performance.
