### ISSUE TITLE
Change in GitHub procedure

### ISSUE THREAD

**Issue by dsegna** [Seneca-CDOT/thecollectors#122]
I would like to propose a minor change to our GitHub procedure to make it easier for me to debug certain things.

I would like to create a debug branch that will leave node id display on, as well as logging certain information in the console. That way when a bug in the map generator is found, you can screenshot the node ids and make a copy of the console information, so I can have the necessary information to solve the issue.

This debug branch would be used the same way we are currently using the master branch, and the master can occasionally be updated from the debug branch with the debugging information taken out.

I'd like to switch to this method so that when either of us encounter a rare bug in the map generator, I can actually have the information needed to address it.

**Comment by ghost** [comment]
Proposal accepted.
