### ISSUE TITLE
should not have 0 as denominator

### ISSUE THREAD

**Issue by cathyatseneca** [Seneca-CDOT/thecollectors#139]
In Map.js file:

Line 5: this.fuel=new Fraction(0,0);

this seems intuitively wrong unless I'm misunderstanding how you are doing it.  Fractions cannot have a 0 denominator.  If you are just trying to init to something, should be 0/1  (which is 0)

**Comment by dsegna** [comment]
You are right it was just an initiation that is not even really necessary. Since this is just a one-line change I will incorporate it when I send the intermediary screen pull request.
