### ISSUE TITLE
Plus/Equal button does not zoom in unless holding Shift

### ISSUE THREAD

**Issue by ghost** [Seneca-CDOT/thecollectors#22]
The code only accepts the + button as the way to zoom in, but players may end up using the button that has both the = and + sign mapped to it, however the button press defaults to an = when pressed without the shift key.

**Comment by dsegna** [comment]
I was using the numpad + and - to zoom. If you want the equal button to also zoom, then it can be added to the key inputs.
I wouldn't call this a bug, as the + button should NOT be triggered when pressing the = without the shift key.

**Comment by ghost** [comment]
Re-labelled as an enhancement.
