### ISSUE TITLE
Tutorial Text Boxes

### ISSUE THREAD

**Issue by dsegna** [Seneca-CDOT/thecollectors#59]
Since the tutorial text boxes are not part of the canvas, mousing over them will cause the canvas to lose focus, meaning input will not work until they return the mouse to the canvas.
This is likely to confuse players when their input stops working after clicking/mousing over the text boxes.
We could either tell them to make sure to return their mouse to the canvas, or possibly think of a better way to do this.

**Comment by ghost** [comment]
The tutorial overlay is still in progress, but as long the pointing device is over the canvas, it should allow for all functionality of the game. We will have to figure out a way for the overlay to still keep the canvas active (assuming we still use divs for the overlay).
