### ISSUE TITLE
Extend the Map class to store the largest denominator generated on the map

### ISSUE THREAD

**Issue by ghost** [Seneca-CDOT/thecollectors#80]
To figure out the least common multiple of the denominators found on the map I need to know what the denominators are. At the very least, I need to know the largest denomination found on the map. Iterating through all the weights to find that denomination would be much more work when the Map can simply store it during the generation of the weights.

The map could go one step further and figure out the LCM of all the denominations itself, and then store that for the game to use, but at minimum I need the Map to store the value for the largest denomination on the map.

**Comment by dsegna** [comment]
At the moment, the largest denominator generated by the map will be the same as the fuel tank denominator.
I think that storing all connections as the same denominator is the easiest, especially for fuel calculations we will have to implement.
I was thinking that each node could just have a chance to display a different denominator (if it can), possibly stored as a "display fraction variable. Internally it would still the same denominator as the fuel for easier calculation purposes.

**Comment by ghost** [comment]
Issue resolved. Map generator guarantees that fractions are all stored in the same denominator behind the scenes and addition/subtraction becomes trivial.
